# Generated by Django 5.0.14 on 2025-07-03 15:33

import django.contrib.auth.password_validation
import django.core.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pendinguser_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь')], default='guest', help_text='Выберите роль пользователя', max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(help_text='Введите адрес электронной почты', max_length=254, unique=True, validators=[users.validators.validate_pending_email], verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(help_text='Пароль должен содержать минимум 8 символов, не может быть полностью числовым, не должен быть похож на имя пользователя и не должен быть слишком простым.', max_length=128, validators=[django.contrib.auth.password_validation.MinimumLengthValidator.validate, django.contrib.auth.password_validation.UserAttributeSimilarityValidator.validate, django.contrib.auth.password_validation.CommonPasswordValidator.validate, django.contrib.auth.password_validation.NumericPasswordValidator.validate]),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='username',
            field=models.CharField(help_text='Имя пользователя должно содержать минимум 4 символов. Допустимые символы: буквы, цифры и .-_', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в имени пользователя. Разрешены только: буквы, цифры и .-_', regex='^[\\w.-]+$'), django.core.validators.MinLengthValidator(limit_value=4, message='Имя пользователя должно содержать минимум 4 символов.'), users.validators.validate_pending_username], verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите адрес электронной почты', max_length=254, unique=True, validators=[users.validators.validate_user_email], verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Пароль должен содержать минимум 8 символов, не может быть полностью числовым, не должен быть похож на имя пользователя и не должен быть слишком простым.', max_length=128, validators=[django.contrib.auth.password_validation.MinimumLengthValidator.validate, django.contrib.auth.password_validation.UserAttributeSimilarityValidator.validate, django.contrib.auth.password_validation.CommonPasswordValidator.validate, django.contrib.auth.password_validation.NumericPasswordValidator.validate]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Имя пользователя должно содержать минимум 4 символов. Допустимые символы: буквы, цифры и .-_', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в имени пользователя. Разрешены только: буквы, цифры и .-_', regex='^[\\w.-]+$'), django.core.validators.MinLengthValidator(limit_value=4, message='Имя пользователя должно содержать минимум 4 символов.'), users.validators.validate_user_username], verbose_name='Имя пользователя'),
        ),
    ]
