# Generated by Django 5.0.14 on 2025-07-04 09:05

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_of_birth_alter_pendinguser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(help_text='Пароль должен содержать минимум 8 символов, не может быть полностью числовым, не должен быть похож на имя пользователя и не должен быть слишком простым.', max_length=128, validators=[django.contrib.auth.password_validation.MinimumLengthValidator.validate, django.contrib.auth.password_validation.UserAttributeSimilarityValidator.validate, django.contrib.auth.password_validation.CommonPasswordValidator.validate, django.contrib.auth.password_validation.NumericPasswordValidator.validate]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Пароль должен содержать минимум 8 символов, не может быть полностью числовым, не должен быть похож на имя пользователя и не должен быть слишком простым.', max_length=128, validators=[django.contrib.auth.password_validation.MinimumLengthValidator.validate, django.contrib.auth.password_validation.UserAttributeSimilarityValidator.validate, django.contrib.auth.password_validation.CommonPasswordValidator.validate, django.contrib.auth.password_validation.NumericPasswordValidator.validate]),
        ),
    ]
