# Generated by Django 3.1.12 on 2025-07-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20250724_2237'),
        ('users', '0017_auto_20250725_1142'),
    ]

    operations = [
    ]
