# Generated by Django 3.1.12 on 2025-07-04 14:06

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('imsi', models.CharField(max_length=15, unique=True)),
                ('schema_version', models.IntegerField(default=1)),
                ('msisdn', djongo.models.fields.JSONField(default=list)),
                ('imeisv', djongo.models.fields.JSONField(default=list)),
                ('mme_host', djongo.models.fields.JSONField(default=list)),
                ('mme_realm', djongo.models.fields.JSONField(default=list)),
                ('purge_flag', djongo.models.fields.JSONField(default=list)),
                ('access_restriction_data', models.IntegerField()),
                ('subscriber_status', models.IntegerField()),
                ('operator_determined_barring', models.IntegerField()),
                ('network_access_mode', models.IntegerField()),
                ('subscribed_rau_tau_timer', models.IntegerField()),
                ('ambr', djongo.models.fields.JSONField(default=dict)),
                ('security', djongo.models.fields.JSONField(default=dict)),
                ('slice', djongo.models.fields.JSONField(default=list)),
                ('_v', models.IntegerField(db_column='__v', default=0)),
                ('mme_timestamp', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'абонент',
                'verbose_name_plural': 'Абоненты',
                'db_table': 'subscribers',
                'managed': False,
            },
        ),
    ]
